<a href="https://colab.research.google.com/github/2000090063/Machine_Learning/blob/main/Random_forest_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np
import seaborn as sns

loading data set 


In [ ]:
df = sns.load_dataset('penguins')
df.head

<bound method NDFrame.head of     species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1  

In [ ]:
df.shape

(344, 7)

In [ ]:
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [ ]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [ ]:
df.dropna(inplace=True)

NameError: ignored

# ***checking the dataset ***

In [ ]:
df.isnull().sum() #null values dropped 

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

# **Feature engineering**

# **one hot encoding transforming categorical data into numeric**

In [ ]:
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
pd.get_dummies(df['sex']).head()

Female  Male
0       0     1
1       1     0
2       1     0
4       1     0
5       0     1

In [ ]:
sex = pd.get_dummies(df['sex'],drop_first=True)
sex.head()

Male
0     1
1     0
2     0
4     0
5     1

# we have dropped one column because only one column is sufficient to determine the gender of penguins either will be male (1) or 0 , that is  female 

Applying one hot encoding to island 

In [ ]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [ ]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [ ]:
island = pd.get_dummies(df['island'],drop_first=True)
island.head(5)

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

# Concatenate the above two data frames to the original df

In [ ]:
new_data = pd.concat([df,island,sex],axis=1)
new_data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Dream  Torgersen  Male  
0       3750.0    Male      0          1     1  
1       3800.0  Female      0          1     0  
2       3250.0  Female      0          1     0  
4       3450.0  Female      0          1     0  
5       3650.0    Male      0          1     1

# Drop the repeated columns

In [ ]:
new_data.drop (['sex','island'],axis=1,inplace=True);
new_data.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Dream  Torgersen  Male  
0      0          1     1  
1      0          1     0  
2      0          1     0  
4      0          1     0  
5      0          1     1

# Creating seperate Target Variable

In [ ]:
Y = new_data.species
Y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [ ]:
Y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [ ]:
Y = Y.map({'Adelie': 0, 'Chinstrap' : 1, 'Gentoo' : 2})
Y.head()


0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

# Dropping target variable : species

In [ ]:
new_data.drop('species',inplace=True, axis=1)
new_data.head()


bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
0            39.1           18.7              181.0       3750.0      0   
1            39.5           17.4              186.0       3800.0      0   
2            40.3           18.0              195.0       3250.0      0   
4            36.7           19.3              193.0       3450.0      0   
5            39.3           20.6              190.0       3650.0      0   

   Torgersen  Male  
0          1     1  
1          1     0  
2          1     0  
4          1     0  
5          1     1

In [ ]:
x=new_data

# Splitting the dataset into training and test dataset 


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,Y_train,Y_test=train_test_split(x,Y, test_size=0.3,random_state=0)



In [ ]:
print ('x_train', x_train.shape)
print ('x_test', x_test.shape)
print ('Y_train', Y_train.shape)
print ('Y_train', Y_train.shape)

x_train (233, 7)
x_test (100, 7)
Y_train (233,)
Y_train (233,)


# Training Random forest classification on training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators= 5 , criterion = 'entropy', random_state = 0)
classifier.fit(x_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

# Predicting the test Results

In [ ]:
Y_pred = classifier.predict(x_test)
Y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

# Confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
cm = confusion_matrix(Y_test,Y_pred)
print(cm)

[[48  0  0]
 [ 2 14  0]
 [ 0  0 36]]


In [ ]:
accuracy_score(Y_test,Y_pred)

0.98

In [ ]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.88      0.93        16
           2       1.00      1.00      1.00        36

    accuracy                           0.98       100
   macro avg       0.99      0.96      0.97       100
weighted avg       0.98      0.98      0.98       100



In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators= 7 , criterion = 'gini', random_state = 0)
classifier.fit(x_train, Y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [ ]:
Y_pred = classifier.predict(x_test)

In [ ]:
accuracy_score(Y_test,Y_pred)

0.99